<template>
  <div>
    <!-- <BackwardNavigation /> -->

    <UtilsHeaderCard
      :title="cardTitle"
      :data="data"
      :display-key="['academic_year', 'code', 'date_start', 'date_end']"
      @edit="$bvModal.show('modal')"
      @delete="deleteAcademicPeriod"
    >
    </UtilsHeaderCard>
    <UtilsBaseCardTab>
      <UtilsCardTab title="Weeks">
        <UtilsFilterComponent>
          <template #besideFilterButton>
            <BaseButton @click="$bvModal.show('week-modal')"
              >Add Weeks</BaseButton
            >
            <BaseButton
              v-if="items.length <= 0"
              @click="
                autoGenerateWeek(data.date_start, data.date_end),
                  $bvModal.show('genWeek')
              "
              >Auto Generate Weeks</BaseButton
            >
          </template>
          <template #default="{ visualization }">
            <TableComponent
              v-if="visualization === 'list'"
              :fields="fields"
              :pages="pages"
              :items="items"
              :busy="busy"
              @page-changed="pageChange"
            />
            <div v-else class="row">
              <div
                v-for="(value, index) in items"
                :key="index"
                class="col-xl-3 col-lg-6 col-md-4 col-sm-6 mb-4"
              >
                <UtilsGridViewCard
                  :data="value"
                  :display-key="['name', 'name', 'week_start', 'week_end']"
                ></UtilsGridViewCard>
              </div>
            </div>
          </template>
        </UtilsFilterComponent>
      </UtilsCardTab>
    </UtilsBaseCardTab>

    <PageConfigurationsPeriodWeekAddEditModal
      title="Add Week"
      :school="school"
      @refresh="pageChange(1)"
    />

    <PageConfigurationsPeriodAddEditModal
      title="Edit Academic Period"
      :school="school"
      :field="data"
      @refresh="$nuxt.refresh()"
    />
    <ModalWrapper
      id="genWeek"
      title="Autogenerated Weeks"
      @ok="handleSubmitAutoGenWeek($event)"
      submitTitle="Create"
    >
      <TableComponent :per-page="genData.length" :items="genData">
      </TableComponent>
    </ModalWrapper>
  </div>
</template>

<script lang="ts">
import mixin from '../mixin'
import TableFunc from '~/mixins/TableCompFun' // Table component mixins
import modalMsgBox from '~/mixins/modalMsgBox'
import genWeeks from '~/mixins/autoGenerateWeek'
export default mixin.extend({
  mixins: [mixin, TableFunc, modalMsgBox, genWeeks],
  async asyncData({ route, $axios }) {
    // const school = store.getters['school/getSchoolByCode'](route.params.id)
    const { data } = await $axios.$get(
      `./slate-admin/period/${route.params.academic_period_id}/`
    )

    return {
      data,
      cardTitle: data.name,
    }
  },

  data() {
    return {
      fields: [
        {
          key: 'name',
          label: 'Name',
          sortable: true,
          // width: '20%',
        },
        {
          key: 'week_start',
          sortable: true,
          // width: '20%',
        },
        {
          key: 'week_end',
          sortable: true,
          // width: '20%',
        },
      ],
      cardTitle: 'Academic Period',
      data: {
        year_start: '',
        year_end: '',
      },
      // AWeek: {
      //   name: '',
      //   week_start: '',
      //   week_end: ''
      // }
    }
  },
  methods: {
    handleOk(event: any) {
      event.preventDefault()
      this.handleSubmit()
    },
    async handleSubmit() {
      try {
        await this.$axios.$post(
          `/slate-admin/school/${this.school.id}/periods/`,
          {
            ...this.AWeek,
            period: this.$route.params.academic_period_id,
            academic_year: '0694b848-f44f-4bfc-9811-d39ce4ca0876',
          }
        )

        await this.$nuxt.refresh()
        ;(this.$refs.week as any).hide()
      } catch (e) {
        console.log(e)
      }
    },

    async pageChange(page: any) {
      this.busy = true
      try {
        const data = await this.$axios.$get(
          `./slate-admin/period/${this.$route.params.academic_period_id}/week/?page=${page}`
        )
        this.items = data.data
        this.pages = data.pages
      } catch (error) {
        console.log(error)
      }
      this.busy = false
    },
    async deleteWeek(id: string) {
      await this.$axios.$delete(`./slate-admin/week/${id}/detail/`)
    },
    async deleteAcademicPeriod() {
      const result = await this.showDeleteMessageBox()
      if (result) {
        try {
          await this.$axios.$delete(`slate-admin/period/${this.data.id}/`)
          this.$router.push({
            name: 'sms-id-administration-configuration-period',
          })
        } catch (error) {
          console.log(error)
        }
      }
    },
  },
  mounted() {
    this.pageChange(1)
  },
})
</script>

<style lang="scss" scoped></style>
