export default {
  data() {
    return {
      allData: {
        quiz_details: {
          id: '',
          created_on: '',
          modified_on: '',
          available_date: '',
          due_date: '',
          subject: '',
          grade_level: '',
          number_of_students_tested: 0,
          status: '',
          image_url: '',
          quiz_meta_data: {
            name: '',
            due_date: '',
            duration: 0,
            quiz_mode: '',
            quiz_type: '',
            essay_item: {
              file_name: '',
              essay_sample_url: '',
              essay_description_item: '',
            },
            full_score: '',
            subject_id: '',
            description: '',
            available_date: '',
          },
          subject_details: {
            id: '',
            code: '',
            name: '',
            color: '',
            icon_data: {
              icon: '',
              icon_base_64: '',
              icon_bg_color: '',
              icon_font_color: '',
            },
          },
          name: '',
          duration: 0,
          description: '',
          active: true,
          mode: 0,
          mean: 0,
          highest_score: 0,
          lowest_score: 0,
          type: '',
          qc_mode: '',
          allow_difficulty: false,
          number_of_students_submitted: 0,
          number_of_students: 0,
          number_of_questions: 0,
          full_score: 0,
          state: '',
          icon_data: {},
          created_by: '',
          last_modified_by: '',
        },
        lesson_name: '',
        lesson_description: '',
        quiz_class: 'Rose',
        quizzes: [],
      },
      data: {
        class: '',
        excercise_type: '',
        subject: '',
        name: '',
        excercise_format: '',
        status: '',
        icon_data: '',
        available_date: '',
        due_date: '',
      },
    }
  },
}
